services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      # - DATABASE_URL=sqlite:///terraform_logs.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000

  # Плагины можно запускать отдельно при необходимости
  # plugin-error-detector:
  #   build: ./plugins
  #   command: ["python", "error_detector.py"]
  #   ports:
  #     - "50051:50051"
